sudo: required
language: java
jdk: openjdk11
dist: xenial

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo apt-get upgrade libstdc++6


script:
  - ./gradlew clean build --refresh-dependencies --stacktrace

notifications:
  email:
    on_success: never
    on_failure: always # default: always
