sudo: required
language: java
jdk: openjdk11
dist: xenial

script:
  - ./gradlew clean build --refresh-dependencies --stacktrace

notifications:
  email:
    on_success: never
    on_failure: always # default: always
