sudo: required
language: java
jdk: openjdk11

before_install:
  - apt-get update
  - apt-get install libstdc++6

script:
  - ./gradlew clean build --refresh-dependencies --stacktrace

notifications:
  email:
    on_success: never
    on_failure: always # default: always
