sudo: required
language: java
jdk: openjdk11

before_install:
  - sudo apt-get update
  - sudo apt-get install libstdc++6

script:
  - ./gradlew build --stacktrace

notifications:
  email:
    on_success: never
    on_failure: always # default: always
